let firstName = 'Carlene';
let lastName = 'James';
let age = 20;
let address = '07/24/1993';
let dateOfBirth = '1016 3rd Street';
console.log('name:', firstName);
console.log('last name:',lastName);
console.log('age:',age);
console.log('address:',address);
console.log('DOB:',dateOfBirth);